services:
  app-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - app-db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  app-db-data:
